name: 'compilestatus'

# This will trigger the action on each push to the `release` branch.
on: workflow_dispatch

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-22.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install vcpkg
        if: matrix.platform == 'windows-latest'
        run: |
          vcpkg integrate install

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libarchive-dev

      - name: install frontend dependencies
        run: | 
          npm install -g pnpm
          pnpm install # change this to npm or pnpm depending on which one you use
          
      - name: build
        run: | 
          npm run tauri build

      - uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          path: |
            src-tauri/target/release/bundle
