name: 'CI - Debug Build'

# This will trigger the action on each push to the `release` branch.
on: workflow_dispatch

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [ macos-latest, ubuntu-22.04, windows-latest ]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install brew packages (macos only)
        if: matrix.platform == 'macos-latest'
        run: |
          brew install pkgconfig
          brew install libarchive
          echo PKG_CONFIG_PATH=$(brew ls libarchive | grep .pc$ | sed 's|/libarchive.pc||') >> $GITHUB_ENV

      - name: cache vcpkg shit (windows only)
        if: matrix.platform == 'windows-latest'
        id: cache-vcpkg
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: C:/vcpkg
          key: ${{ runner.os }}-vcpkg-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-${{ env.cache-name }}
            ${{ runner.os }}-vcpkg-
            ${{ runner.os }}-

      - name: install vcpkg (windows only)
        if: matrix.platform == 'windows-latest'
        run: |
          vcpkg integrate install
          vcpkg install libarchive:x64-windows-static-md 

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libarchive-dev

      - name: install frontend dependencies
        run: |
          npm install -g pnpm
          pnpm install # change this to npm or pnpm depending on which one you use

      - name: build
        run: |
          npm run tauri build --debug

      - uses: actions/upload-artifact@v4
        with:
          name: release-artifacts-${{ matrix.platform }}
          path: |
            src-tauri/target/release/bundle
